### ISSUE TITLE
Implement a 'remember' method

### ISSUE THREAD

**Issue by terah** [tedious/Stash#209] opened 2015-02-06 04:41 UTC
Hi,

Any chance of a 'remember' convenience method that takes a key and callable similar to?: 
https://github.com/cakephp/cache/blob/master/Cache.php#L505

**Comment by terah** [comment] 2015-02-06 04:48
Something like this on Stash\Pool;


```php
    public function remember($name, callable $func, $expires)
    {
        $data = $this->getItem($name)->get();
        if ( ! is_null($data) )
        {
            return $data;
        }
        $data = $func->__invoke();
        try
        {
            if ( ! $this->getItem($name)->set($value, $expires) )
            {
                throw new \Exception("Could not save data to cache");
            }
            return $data;
        }
        catch (\Exception $e)
        {
            $this->logException($e->getMessage(), $e);
            return false;
        }
    }
```

**Comment by Nakard** [comment] 2015-02-06 06:27
As far as I understand it correctly you want to refresh the cache if it has expired. Stash has something like [Stampede Protection](http://www.stashphp.com/Invalidation.html#stampede-protection), you can also lock the item, so other processes won't regenerate it.

Won't that suffice to your needs?

**Comment by terah** [comment] 2015-02-06 09:09
Hi Nakard,

No, the idea would be that if the item is in the cache it is returned otherwise the callable is executed and it's output is pushed in the the cache and returned.  It makes this possible:

```php
$fnExpensiveFunc = function(){
    return aWholeBunchOfDataFromDb();
};
$myData = $myCachePool->remember('myCacheKey', $fnExpensiveFunc, $expiresSecs); 
```

**Comment by tedivm** [comment] 2015-07-07 06:21
Closing this as a dupe of #128

**Closed by tedivm** 2015-07-07 06:21 UTC
